### PR TITLE
[Untested] Fixes issue 14 with Install failing on Linux servers

### PR DESCRIPTION
**Pull request by nel-sam**
This is untested. I tried for a couple hours to get my own private version of this extension in the market without success.
Issue url: https://github.com/aloisdeniel/vsts-flutter-tasks/issues/14

### CODE REVIEW

**Comment by edgarfroes** [comment]
@aloisdeniel are you alive, bro? Your Azure DevOps extension needs you.

**Comment by edgarfroes** [comment]
This package seems to be the working one, since the original package's owner is dead: https://marketplace.visualstudio.com/items?itemName=contrix09.install-flutter-sdk

**Comment by edgarfroes** [comment]
Y'all better off using custom scripts like the one below. Do not waste your time on unmantained extensions.

```
- task: CmdLine@2
  displayName: 'Flutter install'
  inputs:
    script: |
      git clone -b stable https://github.com/flutter/flutter.git
      export FLUTTER_ROOT=`pwd`/flutter/bin
      export PATH=$FLUTTER_ROOT:$PATH
      
      flutter channel stable
      flutter doctor
```

**Comment by aloisdeniel** [comment]
Hi, sorry for the the delay ... but the extension test setup is not friendly (like stated by @nel-sam) at all and reviewing a large PR like this one takes time I don't have right now !

**Comment by edgarfroes** [comment]
> Hi, sorry for the the delay ... but the extension test setup is not friendly (like stated by @nel-sam) at all and reviewing a large PR like this one takes time I don't have right now !
> 
> @edgarfroes Did you try the PR on a private setup ?

Nah, I just went on and made bash scripts and started to call them on my CI's YML setup. Basically cloning flutter stable branch, build and sending to artifact folder for publishing.

Worked just fine for me.

**Comment by aloisdeniel** [comment]
It should be fixed with latest version!

**Pull request closed without merging**
