### PR TITLE
Build & Test task enhancements

### PR DESCRIPTION
**Pull request by Tregan**
-  Added entry-point (--target) option (textfield) to Build task
- Added coverage (--coverage) option (checkbox) to Test task
- Fixed updateGoldens type (bool -> boolean), was appearing as a textfield before

### CODE REVIEW

**Comment by Tregan** [comment]
Actually noticing that enabling the coverage creates an empty lcov.info file. Not sure what's causing this, since the command is executed correctly (.../flutter.bat test --pub --coverage), and when I run that command in a cmd task, the lcov.info file is filled with the code coverage information.

Looking into this.

**Comment by aloisdeniel** [comment]
Thanks !

Can you split the test part in a different PR ? 

This way we could merge the entry point and fix at least.

**Comment by aloisdeniel** [comment]
Update available that fixes `updateGoldens` type ([version 0.2.16](https://marketplace.visualstudio.com/items?itemName=aloisdeniel.flutter)).

**Comment by Tregan** [comment]
Closed so that the branch can be renamed to properly indicate what's being changed. Will make a new PR.

**Pull request closed without merging**
