### PR TITLE
Added aab to platform options, added entry point option

### PR DESCRIPTION
**Pull request by Tregan**
[original PR](https://github.com/aloisdeniel/vsts-flutter-tasks/pull/18)

- Added Android (aab) Target Platform option to Build Task
- Added entry-point (--target) option (textfield) to Build task
- Renamed Android Target Platform option to Android (apk)

### CODE REVIEW

**Comment by jonsamwell** [comment]
It would be great to get this merged in.  Do you need any help to do so?

**Comment by aloisdeniel** [comment]
Thank you, will publish a new version that includes this!

**Comment by MatkovIvan** [comment]
@aloisdeniel @Tregan Does this mean that `all` option builds android twice now?

**Comment by Tregan** [comment]
@MatkovIvan Yeah it does. It builds an ipa, apk (arm only), and an aab (which contains both arm and arm64, ofcourse)

**Pull request merged**
