### PR TITLE
Fixed issue 19 & added coverage option

### PR DESCRIPTION
**Pull request by Tregan**
- Added 'coverage' option to generate code coverage file (lcov.info) to Test Task
- Removed concurrency option (resulted in some tests missing due to race conditions), now always using concurrency=1
- Added 'verbose' option to log run flutter test with the --verbose argument
- Added more RegEx to make sure that cases are recognized (not always formatted the same)

From previous PR (before [split](https://github.com/aloisdeniel/vsts-flutter-tasks/pull/18)):
> Actually noticing that enabling the coverage creates an empty lcov.info file. Not sure what's causing this, since the command is executed correctly (.../flutter.bat test --pub --coverage), and when I run that command in a cmd task, the lcov.info file is filled with the code coverage information.
> 
> Looking into this.
> 
> -EDIT-
> 
> Enabling coverage through the task: "Collecting coverage information..." takes ~15ms -> empty file
> Running "$(FLUTTERTOOLPATH)/flutter test --coverage" through a command line task: "Collecting coverage information..." takes ~25ms -> file contains code coverage information
> Really weird, since the same tests are executed, same results as well, but something's wrong with creating the lcov.info file when collecting coverage information through the test task. Any ideas?

### CODE REVIEW

**Comment by Tregan** [comment]
So I'm trying to see if I can find something, but running the tests locally (added `runner.setInput("coverage", true);` to the basic.js test), seems to work perfectly fine. the lcov.info is generated and contains the coverage information. going to see if it's an issue with my project.

**Comment by Tregan** [comment]
Test script has been rewritten to (hopefully) make sure that all test cases are available in the result set. I have tested the coverage option some more, and it seems to be working fine, except on hosted agents. I've reported a bug here: https://github.com/microsoft/azure-pipelines-image-generation/issues/1174

**Comment by aloisdeniel** [comment]
Thank you, I will review this as soon as I have a little bit more time!

**Comment by evandrom** [comment]
Hello guys, the optional "coverage"is already working? I think that is an amazing improvement to the library! 

Thanks!

**Comment by Tregan** [comment]
@evandrom I was curious myself, and it seems to work now! No idea if it's because of the upgrade to Flutter 1.17 or if Microsoft changed something on their machies, but the lcov file was generated properly. I'll have to do quite a bit of testing/conflict resolving/refactoring, and I might close this PR and split it up into a PR for improved test reporting and a PR for adding code coverage generation.

**Comment by evandrom** [comment]
> @evandrom I was curious myself, and it seems to work now! No idea if it's because of the upgrade to Flutter 1.17 or if Microsoft changed something on their machies, but the lcov file was generated properly. I'll have to do quite a bit of testing/conflict resolving/refactoring, and I might close this PR and split it up into a PR for improved test reporting and a PR for adding code coverage generation.

Great news! Yesterday I tried using the cmdLine@2 and flutter test --coverage. After I used a script that converts the lcov to an cobertura (xml) so it appears after the build with the results. But  to do this Im running the tests twice :(. Hoping soon we can add the optional "coverage" hahaha...Thanks :D

**Pull request closed without merging**
